"""Report generator - Markdown and HTML"""
from datetime import datetime
from pathlib import Path
from config import REPORTS_DIR


class ReportGenerator:
    def __init__(self, session, results: dict = None):
        self.session = session
        self.results = results or {}

    def generate(self, format: str = "markdown") -> str:
        if format == "html":
            return self._generate_html()
        return self._generate_markdown()

    def _generate_markdown(self) -> str:
        s = self.session
        summary = s.summary()
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{s.target}_{ts}.md"
        path = REPORTS_DIR / filename

        severity_emoji = {
            "critical": "CRITICAL",
            "high": "HIGH",
            "medium": "MEDIUM",
            "low": "LOW",
            "info": "INFO",
        }

        content = f"""# PentFlow Report

**Target:** {s.target}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Session:** {s.session_id}
**Status:** {s.status}

---

## Executive Summary

| Severity | Count |
|----------|-------|
| Critical | {summary['critical']} |
| High | {summary['high']} |
| Medium | {summary['medium']} |
| Low | {summary['low']} |
| Info | {summary['info']} |
| **Total** | **{summary['total_findings']}** |

## Methodology

1. **Reconnaissance** - Subdomain enumeration, port scanning, technology fingerprinting, endpoint discovery
2. **Vulnerability Scanning** - Security header analysis, information disclosure checks, vulnerability detection
3. **Exploitation** - XSS testing, SQL injection detection

---

## Findings

"""

        for severity in ["critical", "high", "medium", "low", "info"]:
            findings = s.get_findings_by_severity(severity)
            if findings:
                content += f"### {severity_emoji[severity]} Severity ({len(findings)})\n\n"
                for f in findings:
                    content += f"""#### {f.title}

- **ID:** {f.id}
- **Category:** {f.category}
- **Target:** {f.target}
- **CWE:** {f.cwe or 'N/A'}

**Description:** {f.description}

"""
                    if f.evidence:
                        content += f"**Evidence:**\n```\n{f.evidence}\n```\n\n"
                    if f.remediation:
                        content += f"**Remediation:** {f.remediation}\n\n"
                    content += "---\n\n"

        # Recon results
        if self.results.get("subdomains"):
            content += "## Reconnaissance Results\n\n"
            content += "### Subdomains\n\n"
            for sub in self.results["subdomains"][:50]:
                content += f"- {sub}\n"
            content += "\n"

        if self.results.get("ports"):
            content += "### Open Ports\n\n"
            content += "| Port | State | Service |\n|------|-------|---------|\n"
            for p in self.results["ports"]:
                content += f"| {p['port']} | {p['state']} | {p.get('service', '?')} |\n"
            content += "\n"

        if self.results.get("technologies"):
            content += "### Technologies\n\n"
            for t in self.results["technologies"]:
                content += f"- {t}\n"
            content += "\n"

        content += f"""
---

## Disclaimer

This report was generated by PentFlow for authorized security testing only.
All testing was performed with explicit authorization from the target organization.
The findings should be verified manually before reporting to bug bounty programs.

*Generated by PentFlow v1.0.0*
"""

        path.write_text(content)
        return str(path)

    def _generate_html(self) -> str:
        s = self.session
        summary = s.summary()
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{s.target}_{ts}.html"
        path = REPORTS_DIR / filename

        findings_html = ""
        for severity in ["critical", "high", "medium", "low", "info"]:
            findings = s.get_findings_by_severity(severity)
            color = {"critical": "#ef4444", "high": "#f97316", "medium": "#eab308", "low": "#3b82f6", "info": "#6b7280"}[severity]
            for f in findings:
                findings_html += f"""
                <div class="finding" style="border-left: 4px solid {color}; padding: 15px; margin: 10px 0; background: #1a1a2e; border-radius: 4px;">
                    <h3 style="color: {color}; margin: 0 0 8px 0;">{f.title}</h3>
                    <p><strong>ID:</strong> {f.id} | <strong>Category:</strong> {f.category} | <strong>CWE:</strong> {f.cwe or 'N/A'}</p>
                    <p>{f.description}</p>
                    {"<pre style='background: #0d1117; padding: 10px; border-radius: 4px; overflow-x: auto;'>" + f.evidence + "</pre>" if f.evidence else ""}
                    {"<p><em>Remediation:</em> " + f.remediation + "</p>" if f.remediation else ""}
                </div>
                """

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PentFlow Report - {s.target}</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #0f0f23; color: #e2e8f0; margin: 0; padding: 30px; }}
        h1 {{ color: #00f0ff; border-bottom: 2px solid #00f0ff; padding-bottom: 10px; }}
        h2 {{ color: #00f0ff; margin-top: 30px; }}
        h3 {{ margin: 0; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #1a2332; padding: 10px; text-align: left; }}
        th {{ background: #1a1a2e; color: #00f0ff; }}
        pre {{ background: #0d1117; padding: 15px; border-radius: 6px; overflow-x: auto; }}
        .summary-table {{ max-width: 400px; }}
        .finding {{ margin: 15px 0; }}
    </style>
</head>
<body>
    <h1>PentFlow Report</h1>
    <p><strong>Target:</strong> {s.target} | <strong>Date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M")} | <strong>Session:</strong> {s.session_id}</p>

    <h2>Executive Summary</h2>
    <table class="summary-table">
        <tr><th>Severity</th><th>Count</th></tr>
        <tr><td style="color:#ef4444">Critical</td><td>{summary['critical']}</td></tr>
        <tr><td style="color:#f97316">High</td><td>{summary['high']}</td></tr>
        <tr><td style="color:#eab308">Medium</td><td>{summary['medium']}</td></tr>
        <tr><td style="color:#3b82f6">Low</td><td>{summary['low']}</td></tr>
        <tr><td style="color:#6b7280">Info</td><td>{summary['info']}</td></tr>
        <tr><td><strong>Total</strong></td><td><strong>{summary['total_findings']}</strong></td></tr>
    </table>

    <h2>Findings</h2>
    {findings_html if findings_html else "<p>No findings detected.</p>"}

    <hr style="border-color: #1a2332; margin-top: 40px;">
    <p style="color: #6b7280; font-size: 12px;">Generated by PentFlow v1.0.0 | For authorized security testing only</p>
</body>
</html>"""

        path.write_text(html)
        return str(path)
