"""GitHub export - push reports and results to GitHub repo"""
import json
import subprocess
import os
from pathlib import Path
from datetime import datetime
from config import REPORTS_DIR, BASE_DIR


class GitHubExporter:
    def __init__(self, session, results: dict = None):
        self.session = session
        self.results = results or {}

    def _run(self, cmd: str, cwd: str = None) -> tuple:
        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True, timeout=30, cwd=cwd
            )
            return result.stdout.strip(), result.stderr.strip(), result.returncode
        except Exception as e:
            return "", str(e), 1

    def _ensure_git_config(self):
        self._run('git config user.name "PentFlow"')
        self._run('git config user.email "pentestflow@local"')

    def export(self, repo_name: str = None) -> str:
        if not repo_name:
            repo_name = f"pentest-{self.session.target}-{datetime.now().strftime('%Y%m%d')}"

        export_dir = REPORTS_DIR / repo_name
        export_dir.mkdir(exist_ok=True)

        # Save session data
        session_data = {
            "target": self.session.target,
            "session_id": self.session.session_id,
            "created_at": self.session.created_at,
            "findings": [
                {
                    "id": f.id,
                    "title": f.title,
                    "severity": f.severity,
                    "category": f.category,
                    "target": f.target,
                    "description": f.description,
                    "evidence": f.evidence,
                    "remediation": f.remediation,
                    "cwe": f.cwe,
                }
                for f in self.session.findings
            ],
            "results": self.results,
        }

        (export_dir / "session.json").write_text(json.dumps(session_data, indent=2, default=str))

        # Generate README
        summary = self.session.summary()
        readme = f"""# Pentest Report: {self.session.target}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Session:** {self.session.session_id}
**Total Findings:** {summary['total_findings']}

## Summary

| Severity | Count |
|----------|-------|
| Critical | {summary['critical']} |
| High | {summary['high']} |
| Medium | {summary['medium']} |
| Low | {summary['low']} |
| Info | {summary['info']} |

## Findings

"""
        for f in self.session.findings:
            severity_colors = {"critical": "red", "high": "orange", "medium": "yellow", "low": "blue", "info": "gray"}
            readme += f"- **[{f.severity.upper()}]** {f.title} ({f.category})\n"
            readme += f"  - Target: `{f.target}`\n"
            readme += f"  - Description: {f.description}\n"
            if f.remediation:
                readme += f"  - Fix: {f.remediation}\n"
            readme += "\n"

        readme += f"\n---\n*Generated by PentFlow v1.0.0*\n"
        (export_dir / "README.md").write_text(readme)

        # Copy reports
        for report in REPORTS_DIR.glob(f"report_{self.session.target}_*"):
            (export_dir / report.name).write_text(report.read_text())

        # Git init and commit
        self._ensure_git_config()
        self._run("git init", cwd=str(export_dir))
        self._run("git add -A", cwd=str(export_dir))
        self._run(f'git commit -m "Pentest report: {self.session.target} - {summary["total_findings"]} findings"', cwd=str(export_dir))

        # Try to create repo and push
        stdout, stderr, code = self._run(f"gh repo create {repo_name} --public --source=. --push", cwd=str(export_dir))
        if code == 0:
            return f"https://github.com/{self._get_github_user()}/{repo_name}"

        # Fallback: just return the local path
        return str(export_dir)

    def _get_github_user(self) -> str:
        stdout, _, _ = self._run("gh api user --jq .login")
        return stdout or "unknown"
