"""WAF/IDS Detection — detecta firewalls y sistemas de protección"""
import aiohttp
import time
from core.session import Finding


WAF_FINGERPRINTS = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "body": ["cloudflare", "cf-browser-verification"],
        "status": [403, 503],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "server: akamaighost"],
        "body": ["reference#", "akamai"],
        "status": [403],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "server: amazons3"],
        "body": ["x-amzn-waf", "aws"],
        "status": [403],
    },
    "ModSecurity": {
        "headers": ["server: mod_security", "server: mod_security/"],
        "body": ["mod_security", "modsecurity", "this error was generated by mod_security"],
        "status": [403, 406],
    },
    "Imperva": {
        "headers": ["x-iinfo", "server: imperva"],
        "body": ["imperva", "incapsula"],
        "status": [403],
    },
    "F5 BIG-IP": {
        "headers": ["server: bigip", "server: bigip/"],
        "body": ["bigip", "f5 networks"],
        "status": [403],
    },
    "Barracuda": {
        "headers": ["server: barracuda"],
        "body": ["barracuda"],
        "status": [403],
    },
    "Wordfence": {
        "headers": [],
        "body": ["wordfence", "generated by wordfence"],
        "status": [503],
    },
    "Sucuri": {
        "headers": ["server: sucuri"],
        "body": ["sucuri", "access denied - sucuri"],
        "status": [403],
    },
}

# Triggers to detect WAF reaction
WAF_TRIGGERS = [
    "' OR 1=1--",
    "<script>alert(1)</script>",
    "../../../etc/passwd",
    "{{7*7}}",
    "${7*7}",
]


class WAFDetector:
    def __init__(self, target: str):
        self.target = target
        self.base_url = target if target.startswith("http") else f"https://{target}"

    async def _detect_by_headers(self, headers: dict) -> list:
        detected = []
        headers_lower = {k.lower(): v.lower() for k, v in headers.items()}
        server = headers_lower.get("server", "")

        for waf_name, sigs in WAF_FINGERPRINTS.items():
            # Check response headers
            for h in sigs["headers"]:
                h_lower = h.lower()
                if h_lower.startswith("server:"):
                    if h_lower.split(":", 1)[1].strip() in server:
                        detected.append(waf_name)
                elif h_lower in headers_lower:
                    detected.append(waf_name)

        return list(set(detected))

    async def _detect_by_reaction(self) -> list:
        """Send attack payloads and check if WAF reacts"""
        detected = []
        async with aiohttp.ClientSession() as session:
            for trigger in WAF_TRIGGERS:
                try:
                    test_url = f"{self.base_url}/?q={trigger}"
                    start = time.time()
                    async with session.get(
                        test_url,
                        timeout=aiohttp.ClientTimeout(total=10),
                        ssl=False,
                    ) as resp:
                        elapsed = time.time() - start
                        body = await resp.text()

                        # WAF typically blocks with 403/406/503
                        if resp.status in [403, 406, 503]:
                            body_lower = body.lower()
                            for waf_name, sigs in WAF_FINGERPRINTS.items():
                                for pattern in sigs["body"]:
                                    if pattern.lower() in body_lower:
                                        detected.append(waf_name)

                        # Cloudflare challenge page
                        if "cf-browser-verification" in body or "checking your browser" in body:
                            detected.append("Cloudflare")

                        # Rate limiting detection
                        if resp.status == 429:
                            detected.append("Rate Limiter")

                except Exception:
                    pass

        return list(set(detected))

    async def detect(self) -> list:
        findings = []
        wafs_found = set()

        async with aiohttp.ClientSession() as session:
            try:
                async with session.get(
                    self.base_url,
                    timeout=aiohttp.ClientTimeout(total=10),
                    ssl=False,
                ) as resp:
                    # Detect by headers
                    header_wafs = await self._detect_by_headers(dict(resp.headers))
                    wafs_found.update(header_wafs)

                    # Detect by body
                    body = await resp.text()
                    body_lower = body.lower()
                    for waf_name, sigs in WAF_FINGERPRINTS.items():
                        for pattern in sigs["body"]:
                            if pattern.lower() in body_lower:
                                wafs_found.add(waf_name)

            except Exception:
                pass

        # Detect by reaction to attack payloads
        reaction_wafs = await self._detect_by_reaction()
        wafs_found.update(reaction_wafs)

        # Create findings
        if wafs_found:
            findings.append(Finding(
                id="WAF-DETECTED",
                title=f"WAF/IDS Detected: {', '.join(wafs_found)}",
                severity="info",
                category="WAF Detection",
                target=self.base_url,
                description=f"Target is protected by: {', '.join(wafs_found)}. Adjust scanning approach accordingly.",
                evidence=f"WAFs detected: {', '.join(wafs_found)}",
                remediation="Consider testing on staging environment or adjusting scan rate",
            ))
        else:
            findings.append(Finding(
                id="NO-WAF-DETECTED",
                title="No WAF/IDS Detected",
                severity="info",
                category="WAF Detection",
                target=self.base_url,
                description="No Web Application Firewall or IDS detected. Target may be more vulnerable to automated attacks.",
                remediation="Recommend deploying WAF protection",
            ))

        return findings
